meta_name: "F1 Shot Race"
meta_title: "F1 Shot Race"
meta_description: "F1 Shot Race - The best drinking game in the world"
meta_image: "shot-race-favicon.png" # should exist in `app/assets/images/`
# twitter_account: "@your_twitter_account"   # required for Twitter Cards
